# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joystick Gremlin
url: "https://whitemagic.github.io/JoystickGremlin"

# Generic settings
name: Joystick Gremlin
description:  A tool for configuring and managing joystick devices

# Build settings
markdown: kramdown
highlighter: rogue
